// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _borders_ok_HH_
#define _borders_ok_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct borders_ok : public sc_module {
    // Port declarations 4
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<9> > y;
    sc_in< sc_lv<10> > x;
    sc_out< sc_lv<1> > ap_return;


    // Module declarations
    borders_ok(sc_module_name name);
    SC_HAS_PROCESS(borders_ok);

    ~borders_ok();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<2> > tmp_2826_fu_38_p4;
    sc_signal< sc_lv<1> > tmp_1_fu_32_p2;
    sc_signal< sc_lv<1> > icmp_fu_48_p2;
    sc_signal< sc_lv<1> > tmp2_fu_60_p2;
    sc_signal< sc_lv<1> > tmp_fu_54_p2;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_ready();
    void thread_ap_return();
    void thread_icmp_fu_48_p2();
    void thread_tmp2_fu_60_p2();
    void thread_tmp_1_fu_32_p2();
    void thread_tmp_2826_fu_38_p4();
    void thread_tmp_fu_54_p2();
};

}

using namespace ap_rtl;

#endif
