// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_conv_3x3_strm (
hls::stream<unsigned char > (&out_stream),
hls::stream<unsigned char > (&in_stream));
