// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv_3x3_strm.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv_3x3_strm::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv_3x3_strm::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> conv_3x3_strm::ap_ST_fsm_state1 = "1";
const sc_lv<8> conv_3x3_strm::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<8> conv_3x3_strm::ap_ST_fsm_state4 = "100";
const sc_lv<8> conv_3x3_strm::ap_ST_fsm_pp1_stage0 = "1000";
const sc_lv<8> conv_3x3_strm::ap_ST_fsm_state7 = "10000";
const sc_lv<8> conv_3x3_strm::ap_ST_fsm_state8 = "100000";
const sc_lv<8> conv_3x3_strm::ap_ST_fsm_pp2_stage0 = "1000000";
const sc_lv<8> conv_3x3_strm::ap_ST_fsm_state14 = "10000000";
const sc_lv<32> conv_3x3_strm::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool conv_3x3_strm::ap_const_boolean_1 = true;
const bool conv_3x3_strm::ap_const_boolean_0 = false;
const sc_lv<1> conv_3x3_strm::ap_const_lv1_0 = "0";
const sc_lv<32> conv_3x3_strm::ap_const_lv32_1 = "1";
const sc_lv<32> conv_3x3_strm::ap_const_lv32_3 = "11";
const sc_lv<1> conv_3x3_strm::ap_const_lv1_1 = "1";
const sc_lv<32> conv_3x3_strm::ap_const_lv32_4 = "100";
const sc_lv<32> conv_3x3_strm::ap_const_lv32_6 = "110";
const sc_lv<32> conv_3x3_strm::ap_const_lv32_2 = "10";
const sc_lv<32> conv_3x3_strm::ap_const_lv32_5 = "101";
const sc_lv<9> conv_3x3_strm::ap_const_lv9_FE = "11111110";
const sc_lv<9> conv_3x3_strm::ap_const_lv9_0 = "000000000";
const sc_lv<17> conv_3x3_strm::ap_const_lv17_0 = "00000000000000000";
const sc_lv<64> conv_3x3_strm::ap_const_lv64_FE = "11111110";
const sc_lv<64> conv_3x3_strm::ap_const_lv64_FF = "11111111";
const sc_lv<32> conv_3x3_strm::ap_const_lv32_102 = "100000010";
const sc_lv<9> conv_3x3_strm::ap_const_lv9_100 = "100000000";
const sc_lv<9> conv_3x3_strm::ap_const_lv9_1 = "1";
const sc_lv<32> conv_3x3_strm::ap_const_lv32_8 = "1000";
const sc_lv<9> conv_3x3_strm::ap_const_lv9_2 = "10";
const sc_lv<17> conv_3x3_strm::ap_const_lv17_10000 = "10000000000000000";
const sc_lv<17> conv_3x3_strm::ap_const_lv17_1 = "1";
const sc_lv<9> conv_3x3_strm::ap_const_lv9_3 = "11";
const sc_lv<32> conv_3x3_strm::ap_const_lv32_10 = "10000";
const sc_lv<32> conv_3x3_strm::ap_const_lv32_1F = "11111";
const sc_lv<16> conv_3x3_strm::ap_const_lv16_1 = "1";
const sc_lv<11> conv_3x3_strm::ap_const_lv11_0 = "00000000000";
const sc_lv<32> conv_3x3_strm::ap_const_lv32_A = "1010";
const sc_lv<32> conv_3x3_strm::ap_const_lv32_9 = "1001";
const sc_lv<8> conv_3x3_strm::ap_const_lv8_0 = "00000000";
const sc_lv<32> conv_3x3_strm::ap_const_lv32_7 = "111";

conv_3x3_strm::conv_3x3_strm(sc_module_name name) : sc_module(name), mVcdFile(0) {
    line_buf_0_U = new conv_3x3_strm_linbkb("line_buf_0_U");
    line_buf_0_U->clk(ap_clk);
    line_buf_0_U->reset(ap_rst);
    line_buf_0_U->address0(line_buf_0_address0);
    line_buf_0_U->ce0(line_buf_0_ce0);
    line_buf_0_U->we0(line_buf_0_we0);
    line_buf_0_U->d0(line_buf_0_d0);
    line_buf_0_U->q0(line_buf_0_q0);
    line_buf_0_U->address1(line_buf_0_address1);
    line_buf_0_U->ce1(line_buf_0_ce1);
    line_buf_0_U->q1(line_buf_0_q1);
    line_buf_1_U = new conv_3x3_strm_linbkb("line_buf_1_U");
    line_buf_1_U->clk(ap_clk);
    line_buf_1_U->reset(ap_rst);
    line_buf_1_U->address0(line_buf_1_address0);
    line_buf_1_U->ce0(line_buf_1_ce0);
    line_buf_1_U->we0(line_buf_1_we0);
    line_buf_1_U->d0(in_stream_V_dout);
    line_buf_1_U->q0(line_buf_1_q0);
    line_buf_1_U->address1(line_buf_1_address1);
    line_buf_1_U->ce1(line_buf_1_ce1);
    line_buf_1_U->q1(line_buf_1_q1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp2_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( in_stream_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond1_reg_884 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( in_stream_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond1_reg_884 );

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_11001);
    sensitive << ( in_stream_V_empty_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( exitcond2_reg_893 );

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);
    sensitive << ( in_stream_V_empty_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( exitcond2_reg_893 );

    SC_METHOD(thread_ap_block_pp2_stage0);

    SC_METHOD(thread_ap_block_pp2_stage0_01001);
    sensitive << ( out_stream_V_full_n );
    sensitive << ( in_stream_V_empty_n );
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( ap_reg_pp2_iter3_exitcond_flatten_reg_998 );
    sensitive << ( ap_enable_reg_pp2_iter2 );
    sensitive << ( icmp1_reg_1078 );

    SC_METHOD(thread_ap_block_pp2_stage0_11001);
    sensitive << ( out_stream_V_full_n );
    sensitive << ( in_stream_V_empty_n );
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( ap_reg_pp2_iter3_exitcond_flatten_reg_998 );
    sensitive << ( ap_enable_reg_pp2_iter2 );
    sensitive << ( icmp1_reg_1078 );

    SC_METHOD(thread_ap_block_pp2_stage0_subdone);
    sensitive << ( out_stream_V_full_n );
    sensitive << ( in_stream_V_empty_n );
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( ap_reg_pp2_iter3_exitcond_flatten_reg_998 );
    sensitive << ( ap_enable_reg_pp2_iter2 );
    sensitive << ( icmp1_reg_1078 );

    SC_METHOD(thread_ap_block_state10_pp2_stage0_iter1);

    SC_METHOD(thread_ap_block_state11_pp2_stage0_iter2);
    sensitive << ( in_stream_V_empty_n );
    sensitive << ( icmp1_reg_1078 );

    SC_METHOD(thread_ap_block_state12_pp2_stage0_iter3);

    SC_METHOD(thread_ap_block_state13_pp2_stage0_iter4);
    sensitive << ( out_stream_V_full_n );
    sensitive << ( ap_reg_pp2_iter3_exitcond_flatten_reg_998 );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);
    sensitive << ( in_stream_V_empty_n );
    sensitive << ( exitcond1_reg_884 );

    SC_METHOD(thread_ap_block_state5_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state6_pp1_stage0_iter1);
    sensitive << ( in_stream_V_empty_n );
    sensitive << ( exitcond2_reg_893 );

    SC_METHOD(thread_ap_block_state9_pp2_stage0_iter0);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( exitcond1_fu_310_p2 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state5);
    sensitive << ( exitcond2_fu_327_p2 );

    SC_METHOD(thread_ap_condition_pp2_exit_iter0_state9);
    sensitive << ( exitcond_flatten_fu_415_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_enable_pp2);
    sensitive << ( ap_idle_pp2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_ap_idle_pp2);
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( ap_enable_reg_pp2_iter2 );
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( ap_enable_reg_pp2_iter1 );
    sensitive << ( ap_enable_reg_pp2_iter3 );

    SC_METHOD(thread_ap_phi_mux_x1_phi_fu_268_p4);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( exitcond2_reg_893 );
    sensitive << ( x1_reg_264 );
    sensitive << ( x_2_reg_897 );

    SC_METHOD(thread_ap_phi_mux_x_assign_phi_fu_303_p4);
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( exitcond_flatten_reg_998 );
    sensitive << ( x_assign_reg_299 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( j_reg_1028 );
    sensitive << ( ap_enable_reg_pp2_iter1 );

    SC_METHOD(thread_ap_phi_mux_x_phi_fu_256_p4);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond1_reg_884 );
    sensitive << ( x_reg_252 );
    sensitive << ( x_1_reg_888 );

    SC_METHOD(thread_ap_phi_mux_y_assign_phi_fu_291_p4);
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( exitcond_flatten_reg_998 );
    sensitive << ( y_assign_reg_287 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( y_assign_mid2_reg_1018 );
    sensitive << ( ap_enable_reg_pp2_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_brmerge_demorgan_i_0_1_fu_495_p2);
    sensitive << ( tmp_i_mid2_fu_447_p3 );
    sensitive << ( tmp1_fu_489_p2 );

    SC_METHOD(thread_brmerge_demorgan_i_0_2_fu_521_p2);
    sensitive << ( brmerge_demorgan_i_0_1_fu_495_p2 );
    sensitive << ( rev4_fu_515_p2 );

    SC_METHOD(thread_brmerge_demorgan_i_1_fu_629_p2);
    sensitive << ( brmerge_demorgan_i_0_2_reg_1038 );
    sensitive << ( tmp_i1_mid2_fu_548_p3 );

    SC_METHOD(thread_brmerge_demorgan_i_2_fu_652_p2);
    sensitive << ( brmerge_demorgan_i_1_fu_629_p2 );
    sensitive << ( tmp_i2_mid2_fu_573_p3 );

    SC_METHOD(thread_exitcond1_fu_310_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_x_phi_fu_256_p4 );

    SC_METHOD(thread_exitcond2_fu_327_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_phi_mux_x1_phi_fu_268_p4 );

    SC_METHOD(thread_exitcond_flatten_fu_415_p2);
    sensitive << ( indvar_flatten_reg_276 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_enable_reg_pp2_iter0 );

    SC_METHOD(thread_exitcond_fu_427_p2);
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( exitcond_flatten_fu_415_p2 );
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( ap_phi_mux_x_assign_phi_fu_303_p4 );

    SC_METHOD(thread_i_fu_375_p2);
    sensitive << ( ap_phi_mux_y_assign_phi_fu_291_p4 );

    SC_METHOD(thread_icmp1_fu_668_p2);
    sensitive << ( exitcond_flatten_reg_998 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_enable_reg_pp2_iter1 );
    sensitive << ( tmp_21_fu_658_p4 );

    SC_METHOD(thread_icmp_fu_866_p2);
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_reg_pp2_iter2_exitcond_flatten_reg_998 );
    sensitive << ( ap_enable_reg_pp2_iter3 );
    sensitive << ( tmp_19_fu_856_p4 );

    SC_METHOD(thread_in_stream_V_blk_n);
    sensitive << ( in_stream_V_empty_n );
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond1_reg_884 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( exitcond2_reg_893 );
    sensitive << ( ap_enable_reg_pp2_iter2 );
    sensitive << ( icmp1_reg_1078 );

    SC_METHOD(thread_in_stream_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond1_reg_884 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( exitcond2_reg_893 );
    sensitive << ( ap_enable_reg_pp2_iter2 );
    sensitive << ( icmp1_reg_1078 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_block_pp2_stage0_11001 );

    SC_METHOD(thread_indvar_flatten_next_fu_421_p2);
    sensitive << ( indvar_flatten_reg_276 );

    SC_METHOD(thread_j_fu_469_p2);
    sensitive << ( x_assign_mid2_fu_433_p3 );

    SC_METHOD(thread_line_buf_0_address0);
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( line_buf_0_addr_3_reg_1044 );
    sensitive << ( ap_enable_reg_pp2_iter1 );
    sensitive << ( tmp_1_fu_322_p1 );

    SC_METHOD(thread_line_buf_0_address1);
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( tmp_s_fu_527_p1 );

    SC_METHOD(thread_line_buf_0_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_enable_reg_pp2_iter1 );

    SC_METHOD(thread_line_buf_0_ce1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_enable_reg_pp2_iter0 );

    SC_METHOD(thread_line_buf_0_d0);
    sensitive << ( in_stream_V_dout );
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_enable_reg_pp2_iter1 );
    sensitive << ( line_buf_1_q1 );

    SC_METHOD(thread_line_buf_0_we0);
    sensitive << ( exitcond_flatten_reg_998 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond1_reg_884 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_enable_reg_pp2_iter1 );

    SC_METHOD(thread_line_buf_1_address0);
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp2_iter2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_reg_pp2_iter1_line_buf_1_addr_3_reg_1050 );
    sensitive << ( tmp_4_fu_339_p1 );

    SC_METHOD(thread_line_buf_1_address1);
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( tmp_s_fu_527_p1 );

    SC_METHOD(thread_line_buf_1_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp2_iter2 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_block_pp2_stage0_11001 );

    SC_METHOD(thread_line_buf_1_ce1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_enable_reg_pp2_iter0 );

    SC_METHOD(thread_line_buf_1_we0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( exitcond2_reg_893 );
    sensitive << ( ap_enable_reg_pp2_iter2 );
    sensitive << ( icmp1_reg_1078 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_block_pp2_stage0_11001 );

    SC_METHOD(thread_or_cond1_i_fu_579_p2);
    sensitive << ( tmp_i_mid2_reg_1013 );
    sensitive << ( tmp_1_i_reg_1023 );

    SC_METHOD(thread_out_stream_V_blk_n);
    sensitive << ( out_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( ap_block_pp2_stage0 );
    sensitive << ( ap_reg_pp2_iter3_exitcond_flatten_reg_998 );

    SC_METHOD(thread_out_stream_V_din);
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( ap_reg_pp2_iter3_exitcond_flatten_reg_998 );
    sensitive << ( tmp_14_reg_1087 );
    sensitive << ( icmp_reg_1093 );
    sensitive << ( ap_block_pp2_stage0_01001 );
    sensitive << ( tmp_15_fu_872_p2 );

    SC_METHOD(thread_out_stream_V_write);
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( ap_reg_pp2_iter3_exitcond_flatten_reg_998 );
    sensitive << ( ap_block_pp2_stage0_11001 );

    SC_METHOD(thread_p_neg_fu_816_p2);
    sensitive << ( result_2_i_2_2_fu_802_p3 );

    SC_METHOD(thread_p_shl_cast_fu_642_p1);
    sensitive << ( p_shl_fu_634_p3 );

    SC_METHOD(thread_p_shl_fu_634_p3);
    sensitive << ( window_1_0_1_fu_146 );

    SC_METHOD(thread_read_count_fu_680_p2);
    sensitive << ( read_count_1_fu_122 );

    SC_METHOD(thread_result_0_2_fu_612_p2);
    sensitive << ( tmp_15_0_2_cast_fu_608_p1 );
    sensitive << ( result_2_i_0_0_s_fu_601_p3 );

    SC_METHOD(thread_result_1_2_fu_744_p2);
    sensitive << ( tmp_16_1_2_cast_fu_740_p1 );
    sensitive << ( result_2_i_1_0_s_fu_727_p3 );

    SC_METHOD(thread_result_1_fu_646_p2);
    sensitive << ( result_2_i_0_2_cast_fu_625_p1 );
    sensitive << ( p_shl_cast_fu_642_p1 );

    SC_METHOD(thread_result_2_2_fu_778_p2);
    sensitive << ( tmp_15_2_2_cast_fu_774_p1 );
    sensitive << ( result_2_i_2_0_s_fu_767_p3 );

    SC_METHOD(thread_result_2_fu_761_p2);
    sensitive << ( result_2_i_1_2_fu_750_p3 );
    sensitive << ( tmp_15_2_cast_fu_757_p1 );

    SC_METHOD(thread_result_2_i_0_0_s_fu_601_p3);
    sensitive << ( brmerge_demorgan_i_0_1_reg_1033 );
    sensitive << ( result_2_i_fu_593_p3 );

    SC_METHOD(thread_result_2_i_0_2_cast_fu_625_p1);
    sensitive << ( result_2_i_0_2_fu_618_p3 );

    SC_METHOD(thread_result_2_i_0_2_fu_618_p3);
    sensitive << ( brmerge_demorgan_i_0_2_reg_1038 );
    sensitive << ( result_0_2_fu_612_p2 );

    SC_METHOD(thread_result_2_i_1_0_s_fu_727_p3);
    sensitive << ( brmerge_demorgan_i_1_reg_1061 );
    sensitive << ( result_1_reg_1067 );

    SC_METHOD(thread_result_2_i_1_2_fu_750_p3);
    sensitive << ( brmerge_demorgan_i_1_reg_1061 );
    sensitive << ( result_1_2_fu_744_p2 );

    SC_METHOD(thread_result_2_i_2_0_s_fu_767_p3);
    sensitive << ( brmerge_demorgan_i_2_reg_1072 );
    sensitive << ( result_2_fu_761_p2 );

    SC_METHOD(thread_result_2_i_2_2_fu_802_p3);
    sensitive << ( ap_reg_pp2_iter2_brmerge_demorgan_i_2_reg_1072 );
    sensitive << ( result_2_2_reg_1082 );

    SC_METHOD(thread_result_2_i_fu_593_p3);
    sensitive << ( or_cond1_i_fu_579_p2 );
    sensitive << ( tmp_8_fu_587_p2 );

    SC_METHOD(thread_rev1_fu_409_p2);
    sensitive << ( tmp_6_fu_401_p3 );

    SC_METHOD(thread_rev2_fu_567_p2);
    sensitive << ( tmp_10_fu_559_p3 );

    SC_METHOD(thread_rev3_fu_483_p2);
    sensitive << ( tmp_16_fu_475_p3 );

    SC_METHOD(thread_rev4_fu_515_p2);
    sensitive << ( tmp_17_fu_507_p3 );

    SC_METHOD(thread_rev_fu_389_p2);
    sensitive << ( tmp_3_fu_381_p3 );

    SC_METHOD(thread_tmp1_fu_489_p2);
    sensitive << ( tmp_1_i_fu_463_p2 );
    sensitive << ( rev3_fu_483_p2 );

    SC_METHOD(thread_tmp_10_fu_559_p3);
    sensitive << ( y_assign_2_mid1_fu_553_p2 );

    SC_METHOD(thread_tmp_11_fu_822_p4);
    sensitive << ( p_neg_fu_816_p2 );

    SC_METHOD(thread_tmp_12_fu_832_p2);
    sensitive << ( tmp_11_fu_822_p4 );

    SC_METHOD(thread_tmp_13_fu_838_p4);
    sensitive << ( result_2_i_2_2_fu_802_p3 );

    SC_METHOD(thread_tmp_14_fu_848_p3);
    sensitive << ( tmp_18_fu_808_p3 );
    sensitive << ( tmp_12_fu_832_p2 );
    sensitive << ( tmp_13_fu_838_p4 );

    SC_METHOD(thread_tmp_151_cast_fu_583_p1);
    sensitive << ( window_0_0_1_fu_134 );

    SC_METHOD(thread_tmp_15_0_2_cast_fu_608_p1);
    sensitive << ( window_0_1_fu_126 );

    SC_METHOD(thread_tmp_15_2_2_cast_fu_774_p1);
    sensitive << ( window_2_1_1_fu_150 );

    SC_METHOD(thread_tmp_15_2_cast_fu_757_p1);
    sensitive << ( window_2_0_1_fu_158 );

    SC_METHOD(thread_tmp_15_fu_872_p2);
    sensitive << ( tmp_14_reg_1087 );

    SC_METHOD(thread_tmp_16_1_2_cast_fu_740_p1);
    sensitive << ( tmp_16_1_2_fu_733_p3 );

    SC_METHOD(thread_tmp_16_1_2_fu_733_p3);
    sensitive << ( window_1_1_1_load_reg_1056 );

    SC_METHOD(thread_tmp_16_fu_475_p3);
    sensitive << ( j_fu_469_p2 );

    SC_METHOD(thread_tmp_17_fu_507_p3);
    sensitive << ( x_assign_2_fu_501_p2 );

    SC_METHOD(thread_tmp_18_fu_808_p3);
    sensitive << ( result_2_i_2_2_fu_802_p3 );

    SC_METHOD(thread_tmp_19_fu_856_p4);
    sensitive << ( result_2_i_2_2_fu_802_p3 );

    SC_METHOD(thread_tmp_1_fu_322_p1);
    sensitive << ( x_reg_252 );

    SC_METHOD(thread_tmp_1_i_fu_463_p2);
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( exitcond_flatten_fu_415_p2 );
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( x_assign_mid2_fu_433_p3 );

    SC_METHOD(thread_tmp_21_fu_658_p4);
    sensitive << ( read_count_1_fu_122 );

    SC_METHOD(thread_tmp_3_fu_381_p3);
    sensitive << ( i_fu_375_p2 );

    SC_METHOD(thread_tmp_4_fu_339_p1);
    sensitive << ( x1_reg_264 );

    SC_METHOD(thread_tmp_6_fu_401_p3);
    sensitive << ( y_assign_2_fu_395_p2 );

    SC_METHOD(thread_tmp_8_fu_587_p2);
    sensitive << ( tmp_151_cast_fu_583_p1 );

    SC_METHOD(thread_tmp_i1_mid2_fu_548_p3);
    sensitive << ( rev_reg_987 );
    sensitive << ( rev1_reg_992 );
    sensitive << ( exitcond_reg_1007 );

    SC_METHOD(thread_tmp_i2_mid2_fu_573_p3);
    sensitive << ( rev1_reg_992 );
    sensitive << ( exitcond_reg_1007 );
    sensitive << ( rev2_fu_567_p2 );

    SC_METHOD(thread_tmp_i_fu_369_p2);
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( ap_phi_mux_y_assign_phi_fu_291_p4 );

    SC_METHOD(thread_tmp_i_mid1_fu_441_p2);
    sensitive << ( ap_CS_fsm_pp2_stage0 );
    sensitive << ( ap_block_pp2_stage0_11001 );
    sensitive << ( exitcond_flatten_fu_415_p2 );
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( i_fu_375_p2 );

    SC_METHOD(thread_tmp_i_mid2_fu_447_p3);
    sensitive << ( exitcond_fu_427_p2 );
    sensitive << ( tmp_i_mid1_fu_441_p2 );
    sensitive << ( tmp_i_fu_369_p2 );

    SC_METHOD(thread_tmp_s_fu_527_p1);
    sensitive << ( x_assign_mid2_fu_433_p3 );

    SC_METHOD(thread_x_1_fu_316_p2);
    sensitive << ( ap_phi_mux_x_phi_fu_256_p4 );

    SC_METHOD(thread_x_2_fu_333_p2);
    sensitive << ( ap_phi_mux_x1_phi_fu_268_p4 );

    SC_METHOD(thread_x_assign_2_fu_501_p2);
    sensitive << ( x_assign_mid2_fu_433_p3 );

    SC_METHOD(thread_x_assign_mid2_fu_433_p3);
    sensitive << ( exitcond_fu_427_p2 );
    sensitive << ( ap_phi_mux_x_assign_phi_fu_303_p4 );

    SC_METHOD(thread_y_assign_2_fu_395_p2);
    sensitive << ( ap_phi_mux_y_assign_phi_fu_291_p4 );

    SC_METHOD(thread_y_assign_2_mid1_fu_553_p2);
    sensitive << ( y_assign_reg_287 );

    SC_METHOD(thread_y_assign_mid2_fu_455_p3);
    sensitive << ( exitcond_fu_427_p2 );
    sensitive << ( ap_phi_mux_y_assign_phi_fu_291_p4 );
    sensitive << ( i_fu_375_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp2_iter4 );
    sensitive << ( exitcond1_fu_310_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( exitcond2_fu_327_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( exitcond_flatten_fu_415_p2 );
    sensitive << ( ap_enable_reg_pp2_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp1_stage0_subdone );
    sensitive << ( ap_block_pp2_stage0_subdone );
    sensitive << ( ap_enable_reg_pp2_iter1 );
    sensitive << ( ap_enable_reg_pp2_iter3 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00000001";
    ap_enable_reg_pp2_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp2_iter3 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv_3x3_strm_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, out_stream_V_din, "(port)out_stream_V_din");
    sc_trace(mVcdFile, out_stream_V_full_n, "(port)out_stream_V_full_n");
    sc_trace(mVcdFile, out_stream_V_write, "(port)out_stream_V_write");
    sc_trace(mVcdFile, in_stream_V_dout, "(port)in_stream_V_dout");
    sc_trace(mVcdFile, in_stream_V_empty_n, "(port)in_stream_V_empty_n");
    sc_trace(mVcdFile, in_stream_V_read, "(port)in_stream_V_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, out_stream_V_blk_n, "out_stream_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter4, "ap_enable_reg_pp2_iter4");
    sc_trace(mVcdFile, ap_block_pp2_stage0, "ap_block_pp2_stage0");
    sc_trace(mVcdFile, exitcond_flatten_reg_998, "exitcond_flatten_reg_998");
    sc_trace(mVcdFile, ap_reg_pp2_iter3_exitcond_flatten_reg_998, "ap_reg_pp2_iter3_exitcond_flatten_reg_998");
    sc_trace(mVcdFile, in_stream_V_blk_n, "in_stream_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, exitcond1_reg_884, "exitcond1_reg_884");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, exitcond2_reg_893, "exitcond2_reg_893");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter2, "ap_enable_reg_pp2_iter2");
    sc_trace(mVcdFile, icmp1_reg_1078, "icmp1_reg_1078");
    sc_trace(mVcdFile, x_reg_252, "x_reg_252");
    sc_trace(mVcdFile, x1_reg_264, "x1_reg_264");
    sc_trace(mVcdFile, indvar_flatten_reg_276, "indvar_flatten_reg_276");
    sc_trace(mVcdFile, y_assign_reg_287, "y_assign_reg_287");
    sc_trace(mVcdFile, x_assign_reg_299, "x_assign_reg_299");
    sc_trace(mVcdFile, exitcond1_fu_310_p2, "exitcond1_fu_310_p2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, x_1_fu_316_p2, "x_1_fu_316_p2");
    sc_trace(mVcdFile, x_1_reg_888, "x_1_reg_888");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, exitcond2_fu_327_p2, "exitcond2_fu_327_p2");
    sc_trace(mVcdFile, ap_block_state5_pp1_stage0_iter0, "ap_block_state5_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state6_pp1_stage0_iter1, "ap_block_state6_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, x_2_fu_333_p2, "x_2_fu_333_p2");
    sc_trace(mVcdFile, x_2_reg_897, "x_2_reg_897");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, rev_fu_389_p2, "rev_fu_389_p2");
    sc_trace(mVcdFile, rev_reg_987, "rev_reg_987");
    sc_trace(mVcdFile, ap_CS_fsm_pp2_stage0, "ap_CS_fsm_pp2_stage0");
    sc_trace(mVcdFile, ap_block_state9_pp2_stage0_iter0, "ap_block_state9_pp2_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state10_pp2_stage0_iter1, "ap_block_state10_pp2_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state11_pp2_stage0_iter2, "ap_block_state11_pp2_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state12_pp2_stage0_iter3, "ap_block_state12_pp2_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state13_pp2_stage0_iter4, "ap_block_state13_pp2_stage0_iter4");
    sc_trace(mVcdFile, ap_block_pp2_stage0_11001, "ap_block_pp2_stage0_11001");
    sc_trace(mVcdFile, rev1_fu_409_p2, "rev1_fu_409_p2");
    sc_trace(mVcdFile, rev1_reg_992, "rev1_reg_992");
    sc_trace(mVcdFile, exitcond_flatten_fu_415_p2, "exitcond_flatten_fu_415_p2");
    sc_trace(mVcdFile, ap_reg_pp2_iter1_exitcond_flatten_reg_998, "ap_reg_pp2_iter1_exitcond_flatten_reg_998");
    sc_trace(mVcdFile, ap_reg_pp2_iter2_exitcond_flatten_reg_998, "ap_reg_pp2_iter2_exitcond_flatten_reg_998");
    sc_trace(mVcdFile, indvar_flatten_next_fu_421_p2, "indvar_flatten_next_fu_421_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter0, "ap_enable_reg_pp2_iter0");
    sc_trace(mVcdFile, exitcond_fu_427_p2, "exitcond_fu_427_p2");
    sc_trace(mVcdFile, exitcond_reg_1007, "exitcond_reg_1007");
    sc_trace(mVcdFile, tmp_i_mid2_fu_447_p3, "tmp_i_mid2_fu_447_p3");
    sc_trace(mVcdFile, tmp_i_mid2_reg_1013, "tmp_i_mid2_reg_1013");
    sc_trace(mVcdFile, y_assign_mid2_fu_455_p3, "y_assign_mid2_fu_455_p3");
    sc_trace(mVcdFile, y_assign_mid2_reg_1018, "y_assign_mid2_reg_1018");
    sc_trace(mVcdFile, tmp_1_i_fu_463_p2, "tmp_1_i_fu_463_p2");
    sc_trace(mVcdFile, tmp_1_i_reg_1023, "tmp_1_i_reg_1023");
    sc_trace(mVcdFile, j_fu_469_p2, "j_fu_469_p2");
    sc_trace(mVcdFile, j_reg_1028, "j_reg_1028");
    sc_trace(mVcdFile, brmerge_demorgan_i_0_1_fu_495_p2, "brmerge_demorgan_i_0_1_fu_495_p2");
    sc_trace(mVcdFile, brmerge_demorgan_i_0_1_reg_1033, "brmerge_demorgan_i_0_1_reg_1033");
    sc_trace(mVcdFile, brmerge_demorgan_i_0_2_fu_521_p2, "brmerge_demorgan_i_0_2_fu_521_p2");
    sc_trace(mVcdFile, brmerge_demorgan_i_0_2_reg_1038, "brmerge_demorgan_i_0_2_reg_1038");
    sc_trace(mVcdFile, line_buf_0_addr_3_reg_1044, "line_buf_0_addr_3_reg_1044");
    sc_trace(mVcdFile, line_buf_1_addr_3_reg_1050, "line_buf_1_addr_3_reg_1050");
    sc_trace(mVcdFile, ap_reg_pp2_iter1_line_buf_1_addr_3_reg_1050, "ap_reg_pp2_iter1_line_buf_1_addr_3_reg_1050");
    sc_trace(mVcdFile, window_1_1_1_load_reg_1056, "window_1_1_1_load_reg_1056");
    sc_trace(mVcdFile, brmerge_demorgan_i_1_fu_629_p2, "brmerge_demorgan_i_1_fu_629_p2");
    sc_trace(mVcdFile, brmerge_demorgan_i_1_reg_1061, "brmerge_demorgan_i_1_reg_1061");
    sc_trace(mVcdFile, result_1_fu_646_p2, "result_1_fu_646_p2");
    sc_trace(mVcdFile, result_1_reg_1067, "result_1_reg_1067");
    sc_trace(mVcdFile, brmerge_demorgan_i_2_fu_652_p2, "brmerge_demorgan_i_2_fu_652_p2");
    sc_trace(mVcdFile, brmerge_demorgan_i_2_reg_1072, "brmerge_demorgan_i_2_reg_1072");
    sc_trace(mVcdFile, ap_reg_pp2_iter2_brmerge_demorgan_i_2_reg_1072, "ap_reg_pp2_iter2_brmerge_demorgan_i_2_reg_1072");
    sc_trace(mVcdFile, icmp1_fu_668_p2, "icmp1_fu_668_p2");
    sc_trace(mVcdFile, result_2_2_fu_778_p2, "result_2_2_fu_778_p2");
    sc_trace(mVcdFile, result_2_2_reg_1082, "result_2_2_reg_1082");
    sc_trace(mVcdFile, tmp_14_fu_848_p3, "tmp_14_fu_848_p3");
    sc_trace(mVcdFile, tmp_14_reg_1087, "tmp_14_reg_1087");
    sc_trace(mVcdFile, icmp_fu_866_p2, "icmp_fu_866_p2");
    sc_trace(mVcdFile, icmp_reg_1093, "icmp_reg_1093");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state5, "ap_condition_pp1_exit_iter0_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_block_pp2_stage0_subdone, "ap_block_pp2_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp2_exit_iter0_state9, "ap_condition_pp2_exit_iter0_state9");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter1, "ap_enable_reg_pp2_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp2_iter3, "ap_enable_reg_pp2_iter3");
    sc_trace(mVcdFile, line_buf_0_address0, "line_buf_0_address0");
    sc_trace(mVcdFile, line_buf_0_ce0, "line_buf_0_ce0");
    sc_trace(mVcdFile, line_buf_0_we0, "line_buf_0_we0");
    sc_trace(mVcdFile, line_buf_0_d0, "line_buf_0_d0");
    sc_trace(mVcdFile, line_buf_0_q0, "line_buf_0_q0");
    sc_trace(mVcdFile, line_buf_0_address1, "line_buf_0_address1");
    sc_trace(mVcdFile, line_buf_0_ce1, "line_buf_0_ce1");
    sc_trace(mVcdFile, line_buf_0_q1, "line_buf_0_q1");
    sc_trace(mVcdFile, line_buf_1_address0, "line_buf_1_address0");
    sc_trace(mVcdFile, line_buf_1_ce0, "line_buf_1_ce0");
    sc_trace(mVcdFile, line_buf_1_we0, "line_buf_1_we0");
    sc_trace(mVcdFile, line_buf_1_q0, "line_buf_1_q0");
    sc_trace(mVcdFile, line_buf_1_address1, "line_buf_1_address1");
    sc_trace(mVcdFile, line_buf_1_ce1, "line_buf_1_ce1");
    sc_trace(mVcdFile, line_buf_1_q1, "line_buf_1_q1");
    sc_trace(mVcdFile, ap_phi_mux_x_phi_fu_256_p4, "ap_phi_mux_x_phi_fu_256_p4");
    sc_trace(mVcdFile, ap_phi_mux_x1_phi_fu_268_p4, "ap_phi_mux_x1_phi_fu_268_p4");
    sc_trace(mVcdFile, ap_phi_mux_y_assign_phi_fu_291_p4, "ap_phi_mux_y_assign_phi_fu_291_p4");
    sc_trace(mVcdFile, ap_phi_mux_x_assign_phi_fu_303_p4, "ap_phi_mux_x_assign_phi_fu_303_p4");
    sc_trace(mVcdFile, tmp_1_fu_322_p1, "tmp_1_fu_322_p1");
    sc_trace(mVcdFile, tmp_4_fu_339_p1, "tmp_4_fu_339_p1");
    sc_trace(mVcdFile, tmp_s_fu_527_p1, "tmp_s_fu_527_p1");
    sc_trace(mVcdFile, ap_block_pp2_stage0_01001, "ap_block_pp2_stage0_01001");
    sc_trace(mVcdFile, read_count_1_fu_122, "read_count_1_fu_122");
    sc_trace(mVcdFile, read_count_fu_680_p2, "read_count_fu_680_p2");
    sc_trace(mVcdFile, window_0_1_fu_126, "window_0_1_fu_126");
    sc_trace(mVcdFile, window_0_0_fu_130, "window_0_0_fu_130");
    sc_trace(mVcdFile, window_0_0_1_fu_134, "window_0_0_1_fu_134");
    sc_trace(mVcdFile, window_1_1_1_fu_138, "window_1_1_1_fu_138");
    sc_trace(mVcdFile, window_1_0_fu_142, "window_1_0_fu_142");
    sc_trace(mVcdFile, window_1_0_1_fu_146, "window_1_0_1_fu_146");
    sc_trace(mVcdFile, window_2_1_1_fu_150, "window_2_1_1_fu_150");
    sc_trace(mVcdFile, window_2_0_fu_154, "window_2_0_fu_154");
    sc_trace(mVcdFile, window_2_0_1_fu_158, "window_2_0_1_fu_158");
    sc_trace(mVcdFile, i_fu_375_p2, "i_fu_375_p2");
    sc_trace(mVcdFile, tmp_3_fu_381_p3, "tmp_3_fu_381_p3");
    sc_trace(mVcdFile, y_assign_2_fu_395_p2, "y_assign_2_fu_395_p2");
    sc_trace(mVcdFile, tmp_6_fu_401_p3, "tmp_6_fu_401_p3");
    sc_trace(mVcdFile, tmp_i_mid1_fu_441_p2, "tmp_i_mid1_fu_441_p2");
    sc_trace(mVcdFile, tmp_i_fu_369_p2, "tmp_i_fu_369_p2");
    sc_trace(mVcdFile, x_assign_mid2_fu_433_p3, "x_assign_mid2_fu_433_p3");
    sc_trace(mVcdFile, tmp_16_fu_475_p3, "tmp_16_fu_475_p3");
    sc_trace(mVcdFile, rev3_fu_483_p2, "rev3_fu_483_p2");
    sc_trace(mVcdFile, tmp1_fu_489_p2, "tmp1_fu_489_p2");
    sc_trace(mVcdFile, x_assign_2_fu_501_p2, "x_assign_2_fu_501_p2");
    sc_trace(mVcdFile, tmp_17_fu_507_p3, "tmp_17_fu_507_p3");
    sc_trace(mVcdFile, rev4_fu_515_p2, "rev4_fu_515_p2");
    sc_trace(mVcdFile, y_assign_2_mid1_fu_553_p2, "y_assign_2_mid1_fu_553_p2");
    sc_trace(mVcdFile, tmp_10_fu_559_p3, "tmp_10_fu_559_p3");
    sc_trace(mVcdFile, rev2_fu_567_p2, "rev2_fu_567_p2");
    sc_trace(mVcdFile, tmp_151_cast_fu_583_p1, "tmp_151_cast_fu_583_p1");
    sc_trace(mVcdFile, or_cond1_i_fu_579_p2, "or_cond1_i_fu_579_p2");
    sc_trace(mVcdFile, tmp_8_fu_587_p2, "tmp_8_fu_587_p2");
    sc_trace(mVcdFile, result_2_i_fu_593_p3, "result_2_i_fu_593_p3");
    sc_trace(mVcdFile, tmp_15_0_2_cast_fu_608_p1, "tmp_15_0_2_cast_fu_608_p1");
    sc_trace(mVcdFile, result_2_i_0_0_s_fu_601_p3, "result_2_i_0_0_s_fu_601_p3");
    sc_trace(mVcdFile, result_0_2_fu_612_p2, "result_0_2_fu_612_p2");
    sc_trace(mVcdFile, result_2_i_0_2_fu_618_p3, "result_2_i_0_2_fu_618_p3");
    sc_trace(mVcdFile, tmp_i1_mid2_fu_548_p3, "tmp_i1_mid2_fu_548_p3");
    sc_trace(mVcdFile, p_shl_fu_634_p3, "p_shl_fu_634_p3");
    sc_trace(mVcdFile, result_2_i_0_2_cast_fu_625_p1, "result_2_i_0_2_cast_fu_625_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_642_p1, "p_shl_cast_fu_642_p1");
    sc_trace(mVcdFile, tmp_i2_mid2_fu_573_p3, "tmp_i2_mid2_fu_573_p3");
    sc_trace(mVcdFile, tmp_21_fu_658_p4, "tmp_21_fu_658_p4");
    sc_trace(mVcdFile, tmp_16_1_2_fu_733_p3, "tmp_16_1_2_fu_733_p3");
    sc_trace(mVcdFile, tmp_16_1_2_cast_fu_740_p1, "tmp_16_1_2_cast_fu_740_p1");
    sc_trace(mVcdFile, result_2_i_1_0_s_fu_727_p3, "result_2_i_1_0_s_fu_727_p3");
    sc_trace(mVcdFile, result_1_2_fu_744_p2, "result_1_2_fu_744_p2");
    sc_trace(mVcdFile, result_2_i_1_2_fu_750_p3, "result_2_i_1_2_fu_750_p3");
    sc_trace(mVcdFile, tmp_15_2_cast_fu_757_p1, "tmp_15_2_cast_fu_757_p1");
    sc_trace(mVcdFile, result_2_fu_761_p2, "result_2_fu_761_p2");
    sc_trace(mVcdFile, tmp_15_2_2_cast_fu_774_p1, "tmp_15_2_2_cast_fu_774_p1");
    sc_trace(mVcdFile, result_2_i_2_0_s_fu_767_p3, "result_2_i_2_0_s_fu_767_p3");
    sc_trace(mVcdFile, result_2_i_2_2_fu_802_p3, "result_2_i_2_2_fu_802_p3");
    sc_trace(mVcdFile, p_neg_fu_816_p2, "p_neg_fu_816_p2");
    sc_trace(mVcdFile, tmp_11_fu_822_p4, "tmp_11_fu_822_p4");
    sc_trace(mVcdFile, tmp_18_fu_808_p3, "tmp_18_fu_808_p3");
    sc_trace(mVcdFile, tmp_12_fu_832_p2, "tmp_12_fu_832_p2");
    sc_trace(mVcdFile, tmp_13_fu_838_p4, "tmp_13_fu_838_p4");
    sc_trace(mVcdFile, tmp_19_fu_856_p4, "tmp_19_fu_856_p4");
    sc_trace(mVcdFile, tmp_15_fu_872_p2, "tmp_15_fu_872_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
    sc_trace(mVcdFile, ap_idle_pp2, "ap_idle_pp2");
    sc_trace(mVcdFile, ap_enable_pp2, "ap_enable_pp2");
#endif

    }
    mHdltvinHandle.open("conv_3x3_strm.hdltvin.dat");
    mHdltvoutHandle.open("conv_3x3_strm.hdltvout.dat");
}

conv_3x3_strm::~conv_3x3_strm() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete line_buf_0_U;
    delete line_buf_1_U;
}

void conv_3x3_strm::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state5.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state5.read()))) {
            ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state5.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_enable_reg_pp1_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp2_exit_iter0_state9.read()))) {
            ap_enable_reg_pp2_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
            ap_enable_reg_pp2_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp2_exit_iter0_state9.read())) {
                ap_enable_reg_pp2_iter1 = (ap_condition_pp2_exit_iter0_state9.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp2_iter1 = ap_enable_reg_pp2_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp2_iter2 = ap_enable_reg_pp2_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp2_iter3 = ap_enable_reg_pp2_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp2_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp2_iter4 = ap_enable_reg_pp2_iter3.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
            ap_enable_reg_pp2_iter4 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_415_p2.read()))) {
        indvar_flatten_reg_276 = indvar_flatten_next_fu_421_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        indvar_flatten_reg_276 = ap_const_lv17_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp1_fu_668_p2.read()))) {
        read_count_1_fu_122 = read_count_fu_680_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        read_count_1_fu_122 = ap_const_lv32_102;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp1_fu_668_p2.read()))) {
        window_1_0_fu_142 = window_1_1_1_fu_138.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        window_1_0_fu_142 = line_buf_0_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp1_fu_668_p2.read()))) {
        window_1_1_1_fu_138 = line_buf_1_q1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        window_1_1_1_fu_138 = line_buf_0_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read()) && 
         esl_seteq<1,1,1>(icmp1_reg_1078.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0))) {
        window_2_0_fu_154 = window_2_1_1_fu_150.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        window_2_0_fu_154 = line_buf_1_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read()) && 
         esl_seteq<1,1,1>(icmp1_reg_1078.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0))) {
        window_2_1_1_fu_150 = in_stream_V_dout.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        window_2_1_1_fu_150 = line_buf_1_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x1_reg_264 = ap_const_lv9_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_reg_893.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        x1_reg_264 = x_2_reg_897.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_998.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()))) {
        x_assign_reg_299 = j_reg_1028.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        x_assign_reg_299 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_884.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        x_reg_252 = x_1_reg_888.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        x_reg_252 = ap_const_lv9_FE;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_998.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()))) {
        y_assign_reg_287 = y_assign_mid2_reg_1018.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        y_assign_reg_287 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0))) {
        ap_reg_pp2_iter1_exitcond_flatten_reg_998 = exitcond_flatten_reg_998.read();
        ap_reg_pp2_iter1_line_buf_1_addr_3_reg_1050 = line_buf_1_addr_3_reg_1050.read();
        exitcond_flatten_reg_998 = exitcond_flatten_fu_415_p2.read();
        rev1_reg_992 = rev1_fu_409_p2.read();
        rev_reg_987 = rev_fu_389_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0)) {
        ap_reg_pp2_iter2_brmerge_demorgan_i_2_reg_1072 = brmerge_demorgan_i_2_reg_1072.read();
        ap_reg_pp2_iter2_exitcond_flatten_reg_998 = ap_reg_pp2_iter1_exitcond_flatten_reg_998.read();
        ap_reg_pp2_iter3_exitcond_flatten_reg_998 = ap_reg_pp2_iter2_exitcond_flatten_reg_998.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_415_p2.read()))) {
        brmerge_demorgan_i_0_1_reg_1033 = brmerge_demorgan_i_0_1_fu_495_p2.read();
        brmerge_demorgan_i_0_2_reg_1038 = brmerge_demorgan_i_0_2_fu_521_p2.read();
        exitcond_reg_1007 = exitcond_fu_427_p2.read();
        line_buf_0_addr_3_reg_1044 =  (sc_lv<8>) (tmp_s_fu_527_p1.read());
        line_buf_1_addr_3_reg_1050 =  (sc_lv<8>) (tmp_s_fu_527_p1.read());
        tmp_1_i_reg_1023 = tmp_1_i_fu_463_p2.read();
        tmp_i_mid2_reg_1013 = tmp_i_mid2_fu_447_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_998.read(), ap_const_lv1_0))) {
        brmerge_demorgan_i_1_reg_1061 = brmerge_demorgan_i_1_fu_629_p2.read();
        brmerge_demorgan_i_2_reg_1072 = brmerge_demorgan_i_2_fu_652_p2.read();
        icmp1_reg_1078 = icmp1_fu_668_p2.read();
        result_1_reg_1067 = result_1_fu_646_p2.read();
        window_1_1_1_load_reg_1056 = window_1_1_1_fu_138.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond1_reg_884 = exitcond1_fu_310_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond2_reg_893 = exitcond2_fu_327_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp2_iter2_exitcond_flatten_reg_998.read()))) {
        icmp_reg_1093 = icmp_fu_866_p2.read();
        tmp_14_reg_1087 = tmp_14_fu_848_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_415_p2.read()))) {
        j_reg_1028 = j_fu_469_p2.read();
        y_assign_mid2_reg_1018 = y_assign_mid2_fu_455_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp2_iter1_exitcond_flatten_reg_998.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, brmerge_demorgan_i_2_reg_1072.read()))) {
        result_2_2_reg_1082 = result_2_2_fu_778_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp1_fu_668_p2.read()))) {
        window_0_0_1_fu_134 = window_0_0_fu_130.read();
        window_0_0_fu_130 = window_0_1_fu_126.read();
        window_0_1_fu_126 = line_buf_0_q1.read();
        window_1_0_1_fu_146 = window_1_0_fu_142.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read()) && esl_seteq<1,1,1>(icmp1_reg_1078.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0))) {
        window_2_0_1_fu_158 = window_2_0_fu_154.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_310_p2.read()))) {
        x_1_reg_888 = x_1_fu_316_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        x_2_reg_897 = x_2_fu_333_p2.read();
    }
}

void conv_3x3_strm::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void conv_3x3_strm::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[3];
}

void conv_3x3_strm::thread_ap_CS_fsm_pp2_stage0() {
    ap_CS_fsm_pp2_stage0 = ap_CS_fsm.read()[6];
}

void conv_3x3_strm::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv_3x3_strm::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[7];
}

void conv_3x3_strm::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[2];
}

void conv_3x3_strm::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[4];
}

void conv_3x3_strm::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[5];
}

void conv_3x3_strm::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_3x3_strm::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_884.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_empty_n.read()));
}

void conv_3x3_strm::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_884.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_empty_n.read()));
}

void conv_3x3_strm::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_3x3_strm::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_reg_893.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_empty_n.read()));
}

void conv_3x3_strm::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_reg_893.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_empty_n.read()));
}

void conv_3x3_strm::thread_ap_block_pp2_stage0() {
    ap_block_pp2_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_3x3_strm::thread_ap_block_pp2_stage0_01001() {
    ap_block_pp2_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read()) && 
  esl_seteq<1,1,1>(icmp1_reg_1078.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
  esl_seteq<1,1,1>(ap_reg_pp2_iter3_exitcond_flatten_reg_998.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_stream_V_full_n.read())));
}

void conv_3x3_strm::thread_ap_block_pp2_stage0_11001() {
    ap_block_pp2_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read()) && 
  esl_seteq<1,1,1>(icmp1_reg_1078.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
  esl_seteq<1,1,1>(ap_reg_pp2_iter3_exitcond_flatten_reg_998.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_stream_V_full_n.read())));
}

void conv_3x3_strm::thread_ap_block_pp2_stage0_subdone() {
    ap_block_pp2_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read()) && 
  esl_seteq<1,1,1>(icmp1_reg_1078.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
  esl_seteq<1,1,1>(ap_reg_pp2_iter3_exitcond_flatten_reg_998.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_stream_V_full_n.read())));
}

void conv_3x3_strm::thread_ap_block_state10_pp2_stage0_iter1() {
    ap_block_state10_pp2_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_3x3_strm::thread_ap_block_state11_pp2_stage0_iter2() {
    ap_block_state11_pp2_stage0_iter2 = (esl_seteq<1,1,1>(icmp1_reg_1078.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_empty_n.read()));
}

void conv_3x3_strm::thread_ap_block_state12_pp2_stage0_iter3() {
    ap_block_state12_pp2_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_3x3_strm::thread_ap_block_state13_pp2_stage0_iter4() {
    ap_block_state13_pp2_stage0_iter4 = (esl_seteq<1,1,1>(ap_reg_pp2_iter3_exitcond_flatten_reg_998.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, out_stream_V_full_n.read()));
}

void conv_3x3_strm::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_3x3_strm::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_884.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_empty_n.read()));
}

void conv_3x3_strm::thread_ap_block_state5_pp1_stage0_iter0() {
    ap_block_state5_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_3x3_strm::thread_ap_block_state6_pp1_stage0_iter1() {
    ap_block_state6_pp1_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_reg_893.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_empty_n.read()));
}

void conv_3x3_strm::thread_ap_block_state9_pp2_stage0_iter0() {
    ap_block_state9_pp2_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_3x3_strm::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_310_p2.read())) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_ap_condition_pp1_exit_iter0_state5() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_327_p2.read())) {
        ap_condition_pp1_exit_iter0_state5 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state5 = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_ap_condition_pp2_exit_iter0_state9() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten_fu_415_p2.read())) {
        ap_condition_pp2_exit_iter0_state9 = ap_const_logic_1;
    } else {
        ap_condition_pp2_exit_iter0_state9 = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void conv_3x3_strm::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void conv_3x3_strm::thread_ap_enable_pp2() {
    ap_enable_pp2 = (ap_idle_pp2.read() ^ ap_const_logic_1);
}

void conv_3x3_strm::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_ap_idle_pp2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp2_iter4.read()))) {
        ap_idle_pp2 = ap_const_logic_1;
    } else {
        ap_idle_pp2 = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_ap_phi_mux_x1_phi_fu_268_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_reg_893.read()))) {
        ap_phi_mux_x1_phi_fu_268_p4 = x_2_reg_897.read();
    } else {
        ap_phi_mux_x1_phi_fu_268_p4 = x1_reg_264.read();
    }
}

void conv_3x3_strm::thread_ap_phi_mux_x_assign_phi_fu_303_p4() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_998.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()))) {
        ap_phi_mux_x_assign_phi_fu_303_p4 = j_reg_1028.read();
    } else {
        ap_phi_mux_x_assign_phi_fu_303_p4 = x_assign_reg_299.read();
    }
}

void conv_3x3_strm::thread_ap_phi_mux_x_phi_fu_256_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_884.read()))) {
        ap_phi_mux_x_phi_fu_256_p4 = x_1_reg_888.read();
    } else {
        ap_phi_mux_x_phi_fu_256_p4 = x_reg_252.read();
    }
}

void conv_3x3_strm::thread_ap_phi_mux_y_assign_phi_fu_291_p4() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_998.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()))) {
        ap_phi_mux_y_assign_phi_fu_291_p4 = y_assign_mid2_reg_1018.read();
    } else {
        ap_phi_mux_y_assign_phi_fu_291_p4 = y_assign_reg_287.read();
    }
}

void conv_3x3_strm::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_brmerge_demorgan_i_0_1_fu_495_p2() {
    brmerge_demorgan_i_0_1_fu_495_p2 = (tmp1_fu_489_p2.read() & tmp_i_mid2_fu_447_p3.read());
}

void conv_3x3_strm::thread_brmerge_demorgan_i_0_2_fu_521_p2() {
    brmerge_demorgan_i_0_2_fu_521_p2 = (brmerge_demorgan_i_0_1_fu_495_p2.read() & rev4_fu_515_p2.read());
}

void conv_3x3_strm::thread_brmerge_demorgan_i_1_fu_629_p2() {
    brmerge_demorgan_i_1_fu_629_p2 = (tmp_i1_mid2_fu_548_p3.read() & brmerge_demorgan_i_0_2_reg_1038.read());
}

void conv_3x3_strm::thread_brmerge_demorgan_i_2_fu_652_p2() {
    brmerge_demorgan_i_2_fu_652_p2 = (tmp_i2_mid2_fu_573_p3.read() & brmerge_demorgan_i_1_fu_629_p2.read());
}

void conv_3x3_strm::thread_exitcond1_fu_310_p2() {
    exitcond1_fu_310_p2 = (!ap_phi_mux_x_phi_fu_256_p4.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_x_phi_fu_256_p4.read() == ap_const_lv9_100);
}

void conv_3x3_strm::thread_exitcond2_fu_327_p2() {
    exitcond2_fu_327_p2 = (!ap_phi_mux_x1_phi_fu_268_p4.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_x1_phi_fu_268_p4.read() == ap_const_lv9_100);
}

void conv_3x3_strm::thread_exitcond_flatten_fu_415_p2() {
    exitcond_flatten_fu_415_p2 = (!indvar_flatten_reg_276.read().is_01() || !ap_const_lv17_10000.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_276.read() == ap_const_lv17_10000);
}

void conv_3x3_strm::thread_exitcond_fu_427_p2() {
    exitcond_fu_427_p2 = (!ap_phi_mux_x_assign_phi_fu_303_p4.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_x_assign_phi_fu_303_p4.read() == ap_const_lv9_100);
}

void conv_3x3_strm::thread_i_fu_375_p2() {
    i_fu_375_p2 = (!ap_phi_mux_y_assign_phi_fu_291_p4.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(ap_phi_mux_y_assign_phi_fu_291_p4.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void conv_3x3_strm::thread_icmp1_fu_668_p2() {
    icmp1_fu_668_p2 = (!tmp_21_fu_658_p4.read().is_01() || !ap_const_lv16_1.is_01())? sc_lv<1>(): (sc_bigint<16>(tmp_21_fu_658_p4.read()) < sc_bigint<16>(ap_const_lv16_1));
}

void conv_3x3_strm::thread_icmp_fu_866_p2() {
    icmp_fu_866_p2 = (!tmp_19_fu_856_p4.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): (sc_bigint<9>(tmp_19_fu_856_p4.read()) > sc_bigint<9>(ap_const_lv9_0));
}

void conv_3x3_strm::thread_in_stream_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_884.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_reg_893.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read()) && 
          esl_seteq<1,1,1>(icmp1_reg_1078.read(), ap_const_lv1_1)))) {
        in_stream_V_blk_n = in_stream_V_empty_n.read();
    } else {
        in_stream_V_blk_n = ap_const_logic_1;
    }
}

void conv_3x3_strm::thread_in_stream_V_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_884.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_reg_893.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read()) && 
          esl_seteq<1,1,1>(icmp1_reg_1078.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0)))) {
        in_stream_V_read = ap_const_logic_1;
    } else {
        in_stream_V_read = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_indvar_flatten_next_fu_421_p2() {
    indvar_flatten_next_fu_421_p2 = (!indvar_flatten_reg_276.read().is_01() || !ap_const_lv17_1.is_01())? sc_lv<17>(): (sc_biguint<17>(indvar_flatten_reg_276.read()) + sc_biguint<17>(ap_const_lv17_1));
}

void conv_3x3_strm::thread_j_fu_469_p2() {
    j_fu_469_p2 = (!x_assign_mid2_fu_433_p3.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(x_assign_mid2_fu_433_p3.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void conv_3x3_strm::thread_line_buf_0_address0() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()))) {
        line_buf_0_address0 = line_buf_0_addr_3_reg_1044.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        line_buf_0_address0 =  (sc_lv<8>) (ap_const_lv64_FE);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        line_buf_0_address0 =  (sc_lv<8>) (tmp_1_fu_322_p1.read());
    } else {
        line_buf_0_address0 = "XXXXXXXX";
    }
}

void conv_3x3_strm::thread_line_buf_0_address1() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read()))) {
        line_buf_0_address1 =  (sc_lv<8>) (tmp_s_fu_527_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        line_buf_0_address1 =  (sc_lv<8>) (ap_const_lv64_FF);
    } else {
        line_buf_0_address1 = "XXXXXXXX";
    }
}

void conv_3x3_strm::thread_line_buf_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read())))) {
        line_buf_0_ce0 = ap_const_logic_1;
    } else {
        line_buf_0_ce0 = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_line_buf_0_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read())))) {
        line_buf_0_ce1 = ap_const_logic_1;
    } else {
        line_buf_0_ce1 = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_line_buf_0_d0() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read()))) {
        line_buf_0_d0 = line_buf_1_q1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        line_buf_0_d0 = in_stream_V_dout.read();
    } else {
        line_buf_0_d0 = "XXXXXXXX";
    }
}

void conv_3x3_strm::thread_line_buf_0_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_reg_884.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(exitcond_flatten_reg_998.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter1.read())))) {
        line_buf_0_we0 = ap_const_logic_1;
    } else {
        line_buf_0_we0 = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_line_buf_1_address0() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read()))) {
        line_buf_1_address0 = ap_reg_pp2_iter1_line_buf_1_addr_3_reg_1050.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        line_buf_1_address0 =  (sc_lv<8>) (ap_const_lv64_FE);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        line_buf_1_address0 =  (sc_lv<8>) (tmp_4_fu_339_p1.read());
    } else {
        line_buf_1_address0 = "XXXXXXXX";
    }
}

void conv_3x3_strm::thread_line_buf_1_address1() {
    if ((esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read()))) {
        line_buf_1_address1 =  (sc_lv<8>) (tmp_s_fu_527_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        line_buf_1_address1 =  (sc_lv<8>) (ap_const_lv64_FF);
    } else {
        line_buf_1_address1 = "XXXXXXXX";
    }
}

void conv_3x3_strm::thread_line_buf_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0)))) {
        line_buf_1_ce0 = ap_const_logic_1;
    } else {
        line_buf_1_ce0 = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_line_buf_1_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp2_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read())))) {
        line_buf_1_ce1 = ap_const_logic_1;
    } else {
        line_buf_1_ce1 = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_line_buf_1_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_reg_893.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter2.read()) && 
          esl_seteq<1,1,1>(icmp1_reg_1078.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0)))) {
        line_buf_1_we0 = ap_const_logic_1;
    } else {
        line_buf_1_we0 = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_or_cond1_i_fu_579_p2() {
    or_cond1_i_fu_579_p2 = (tmp_i_mid2_reg_1013.read() & tmp_1_i_reg_1023.read());
}

void conv_3x3_strm::thread_out_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
         esl_seteq<1,1,1>(ap_block_pp2_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_reg_pp2_iter3_exitcond_flatten_reg_998.read(), ap_const_lv1_0))) {
        out_stream_V_blk_n = out_stream_V_full_n.read();
    } else {
        out_stream_V_blk_n = ap_const_logic_1;
    }
}

void conv_3x3_strm::thread_out_stream_V_din() {
    out_stream_V_din = (!icmp_reg_1093.read()[0].is_01())? sc_lv<8>(): ((icmp_reg_1093.read()[0].to_bool())? tmp_14_reg_1087.read(): tmp_15_fu_872_p2.read());
}

void conv_3x3_strm::thread_out_stream_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
         esl_seteq<1,1,1>(ap_reg_pp2_iter3_exitcond_flatten_reg_998.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp2_stage0_11001.read(), ap_const_boolean_0))) {
        out_stream_V_write = ap_const_logic_1;
    } else {
        out_stream_V_write = ap_const_logic_0;
    }
}

void conv_3x3_strm::thread_p_neg_fu_816_p2() {
    p_neg_fu_816_p2 = (!ap_const_lv11_0.is_01() || !result_2_i_2_2_fu_802_p3.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_0) - sc_biguint<11>(result_2_i_2_2_fu_802_p3.read()));
}

void conv_3x3_strm::thread_p_shl_cast_fu_642_p1() {
    p_shl_cast_fu_642_p1 = esl_zext<11,9>(p_shl_fu_634_p3.read());
}

void conv_3x3_strm::thread_p_shl_fu_634_p3() {
    p_shl_fu_634_p3 = esl_concat<8,1>(window_1_0_1_fu_146.read(), ap_const_lv1_0);
}

void conv_3x3_strm::thread_read_count_fu_680_p2() {
    read_count_fu_680_p2 = (!read_count_1_fu_122.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(read_count_1_fu_122.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void conv_3x3_strm::thread_result_0_2_fu_612_p2() {
    result_0_2_fu_612_p2 = (!tmp_15_0_2_cast_fu_608_p1.read().is_01() || !result_2_i_0_0_s_fu_601_p3.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_15_0_2_cast_fu_608_p1.read()) + sc_biguint<9>(result_2_i_0_0_s_fu_601_p3.read()));
}

void conv_3x3_strm::thread_result_1_2_fu_744_p2() {
    result_1_2_fu_744_p2 = (!tmp_16_1_2_cast_fu_740_p1.read().is_01() || !result_2_i_1_0_s_fu_727_p3.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_16_1_2_cast_fu_740_p1.read()) + sc_biguint<11>(result_2_i_1_0_s_fu_727_p3.read()));
}

void conv_3x3_strm::thread_result_1_fu_646_p2() {
    result_1_fu_646_p2 = (!result_2_i_0_2_cast_fu_625_p1.read().is_01() || !p_shl_cast_fu_642_p1.read().is_01())? sc_lv<11>(): (sc_bigint<11>(result_2_i_0_2_cast_fu_625_p1.read()) - sc_biguint<11>(p_shl_cast_fu_642_p1.read()));
}

void conv_3x3_strm::thread_result_2_2_fu_778_p2() {
    result_2_2_fu_778_p2 = (!tmp_15_2_2_cast_fu_774_p1.read().is_01() || !result_2_i_2_0_s_fu_767_p3.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_15_2_2_cast_fu_774_p1.read()) + sc_biguint<11>(result_2_i_2_0_s_fu_767_p3.read()));
}

void conv_3x3_strm::thread_result_2_fu_761_p2() {
    result_2_fu_761_p2 = (!result_2_i_1_2_fu_750_p3.read().is_01() || !tmp_15_2_cast_fu_757_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(result_2_i_1_2_fu_750_p3.read()) - sc_biguint<11>(tmp_15_2_cast_fu_757_p1.read()));
}

void conv_3x3_strm::thread_result_2_i_0_0_s_fu_601_p3() {
    result_2_i_0_0_s_fu_601_p3 = (!brmerge_demorgan_i_0_1_reg_1033.read()[0].is_01())? sc_lv<9>(): ((brmerge_demorgan_i_0_1_reg_1033.read()[0].to_bool())? result_2_i_fu_593_p3.read(): ap_const_lv9_0);
}

void conv_3x3_strm::thread_result_2_i_0_2_cast_fu_625_p1() {
    result_2_i_0_2_cast_fu_625_p1 = esl_sext<11,9>(result_2_i_0_2_fu_618_p3.read());
}

void conv_3x3_strm::thread_result_2_i_0_2_fu_618_p3() {
    result_2_i_0_2_fu_618_p3 = (!brmerge_demorgan_i_0_2_reg_1038.read()[0].is_01())? sc_lv<9>(): ((brmerge_demorgan_i_0_2_reg_1038.read()[0].to_bool())? result_0_2_fu_612_p2.read(): ap_const_lv9_0);
}

void conv_3x3_strm::thread_result_2_i_1_0_s_fu_727_p3() {
    result_2_i_1_0_s_fu_727_p3 = (!brmerge_demorgan_i_1_reg_1061.read()[0].is_01())? sc_lv<11>(): ((brmerge_demorgan_i_1_reg_1061.read()[0].to_bool())? result_1_reg_1067.read(): ap_const_lv11_0);
}

void conv_3x3_strm::thread_result_2_i_1_2_fu_750_p3() {
    result_2_i_1_2_fu_750_p3 = (!brmerge_demorgan_i_1_reg_1061.read()[0].is_01())? sc_lv<11>(): ((brmerge_demorgan_i_1_reg_1061.read()[0].to_bool())? result_1_2_fu_744_p2.read(): ap_const_lv11_0);
}

void conv_3x3_strm::thread_result_2_i_2_0_s_fu_767_p3() {
    result_2_i_2_0_s_fu_767_p3 = (!brmerge_demorgan_i_2_reg_1072.read()[0].is_01())? sc_lv<11>(): ((brmerge_demorgan_i_2_reg_1072.read()[0].to_bool())? result_2_fu_761_p2.read(): ap_const_lv11_0);
}

void conv_3x3_strm::thread_result_2_i_2_2_fu_802_p3() {
    result_2_i_2_2_fu_802_p3 = (!ap_reg_pp2_iter2_brmerge_demorgan_i_2_reg_1072.read()[0].is_01())? sc_lv<11>(): ((ap_reg_pp2_iter2_brmerge_demorgan_i_2_reg_1072.read()[0].to_bool())? result_2_2_reg_1082.read(): ap_const_lv11_0);
}

void conv_3x3_strm::thread_result_2_i_fu_593_p3() {
    result_2_i_fu_593_p3 = (!or_cond1_i_fu_579_p2.read()[0].is_01())? sc_lv<9>(): ((or_cond1_i_fu_579_p2.read()[0].to_bool())? tmp_8_fu_587_p2.read(): ap_const_lv9_0);
}

void conv_3x3_strm::thread_rev1_fu_409_p2() {
    rev1_fu_409_p2 = (tmp_6_fu_401_p3.read() ^ ap_const_lv1_1);
}

void conv_3x3_strm::thread_rev2_fu_567_p2() {
    rev2_fu_567_p2 = (tmp_10_fu_559_p3.read() ^ ap_const_lv1_1);
}

void conv_3x3_strm::thread_rev3_fu_483_p2() {
    rev3_fu_483_p2 = (tmp_16_fu_475_p3.read() ^ ap_const_lv1_1);
}

void conv_3x3_strm::thread_rev4_fu_515_p2() {
    rev4_fu_515_p2 = (tmp_17_fu_507_p3.read() ^ ap_const_lv1_1);
}

void conv_3x3_strm::thread_rev_fu_389_p2() {
    rev_fu_389_p2 = (tmp_3_fu_381_p3.read() ^ ap_const_lv1_1);
}

void conv_3x3_strm::thread_tmp1_fu_489_p2() {
    tmp1_fu_489_p2 = (tmp_1_i_fu_463_p2.read() & rev3_fu_483_p2.read());
}

void conv_3x3_strm::thread_tmp_10_fu_559_p3() {
    tmp_10_fu_559_p3 = y_assign_2_mid1_fu_553_p2.read().range(8, 8);
}

void conv_3x3_strm::thread_tmp_11_fu_822_p4() {
    tmp_11_fu_822_p4 = p_neg_fu_816_p2.read().range(9, 2);
}

void conv_3x3_strm::thread_tmp_12_fu_832_p2() {
    tmp_12_fu_832_p2 = (!ap_const_lv8_0.is_01() || !tmp_11_fu_822_p4.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_0) - sc_biguint<8>(tmp_11_fu_822_p4.read()));
}

void conv_3x3_strm::thread_tmp_13_fu_838_p4() {
    tmp_13_fu_838_p4 = result_2_i_2_2_fu_802_p3.read().range(9, 2);
}

void conv_3x3_strm::thread_tmp_14_fu_848_p3() {
    tmp_14_fu_848_p3 = (!tmp_18_fu_808_p3.read()[0].is_01())? sc_lv<8>(): ((tmp_18_fu_808_p3.read()[0].to_bool())? tmp_12_fu_832_p2.read(): tmp_13_fu_838_p4.read());
}

void conv_3x3_strm::thread_tmp_151_cast_fu_583_p1() {
    tmp_151_cast_fu_583_p1 = esl_zext<9,8>(window_0_0_1_fu_134.read());
}

void conv_3x3_strm::thread_tmp_15_0_2_cast_fu_608_p1() {
    tmp_15_0_2_cast_fu_608_p1 = esl_zext<9,8>(window_0_1_fu_126.read());
}

void conv_3x3_strm::thread_tmp_15_2_2_cast_fu_774_p1() {
    tmp_15_2_2_cast_fu_774_p1 = esl_zext<11,8>(window_2_1_1_fu_150.read());
}

void conv_3x3_strm::thread_tmp_15_2_cast_fu_757_p1() {
    tmp_15_2_cast_fu_757_p1 = esl_zext<11,8>(window_2_0_1_fu_158.read());
}

void conv_3x3_strm::thread_tmp_15_fu_872_p2() {
    tmp_15_fu_872_p2 = (!ap_const_lv8_0.is_01() || !tmp_14_reg_1087.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_0) - sc_biguint<8>(tmp_14_reg_1087.read()));
}

void conv_3x3_strm::thread_tmp_16_1_2_cast_fu_740_p1() {
    tmp_16_1_2_cast_fu_740_p1 = esl_zext<11,9>(tmp_16_1_2_fu_733_p3.read());
}

void conv_3x3_strm::thread_tmp_16_1_2_fu_733_p3() {
    tmp_16_1_2_fu_733_p3 = esl_concat<8,1>(window_1_1_1_load_reg_1056.read(), ap_const_lv1_0);
}

void conv_3x3_strm::thread_tmp_16_fu_475_p3() {
    tmp_16_fu_475_p3 = j_fu_469_p2.read().range(8, 8);
}

void conv_3x3_strm::thread_tmp_17_fu_507_p3() {
    tmp_17_fu_507_p3 = x_assign_2_fu_501_p2.read().range(8, 8);
}

void conv_3x3_strm::thread_tmp_18_fu_808_p3() {
    tmp_18_fu_808_p3 = result_2_i_2_2_fu_802_p3.read().range(10, 10);
}

void conv_3x3_strm::thread_tmp_19_fu_856_p4() {
    tmp_19_fu_856_p4 = result_2_i_2_2_fu_802_p3.read().range(10, 2);
}

void conv_3x3_strm::thread_tmp_1_fu_322_p1() {
    tmp_1_fu_322_p1 = esl_zext<64,9>(x_reg_252.read());
}

void conv_3x3_strm::thread_tmp_1_i_fu_463_p2() {
    tmp_1_i_fu_463_p2 = (!x_assign_mid2_fu_433_p3.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): sc_lv<1>(x_assign_mid2_fu_433_p3.read() != ap_const_lv9_0);
}

void conv_3x3_strm::thread_tmp_21_fu_658_p4() {
    tmp_21_fu_658_p4 = read_count_1_fu_122.read().range(31, 16);
}

void conv_3x3_strm::thread_tmp_3_fu_381_p3() {
    tmp_3_fu_381_p3 = i_fu_375_p2.read().range(8, 8);
}

void conv_3x3_strm::thread_tmp_4_fu_339_p1() {
    tmp_4_fu_339_p1 = esl_zext<64,9>(x1_reg_264.read());
}

void conv_3x3_strm::thread_tmp_6_fu_401_p3() {
    tmp_6_fu_401_p3 = y_assign_2_fu_395_p2.read().range(8, 8);
}

void conv_3x3_strm::thread_tmp_8_fu_587_p2() {
    tmp_8_fu_587_p2 = (!ap_const_lv9_0.is_01() || !tmp_151_cast_fu_583_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_0) - sc_biguint<9>(tmp_151_cast_fu_583_p1.read()));
}

void conv_3x3_strm::thread_tmp_i1_mid2_fu_548_p3() {
    tmp_i1_mid2_fu_548_p3 = (!exitcond_reg_1007.read()[0].is_01())? sc_lv<1>(): ((exitcond_reg_1007.read()[0].to_bool())? rev1_reg_992.read(): rev_reg_987.read());
}

void conv_3x3_strm::thread_tmp_i2_mid2_fu_573_p3() {
    tmp_i2_mid2_fu_573_p3 = (!exitcond_reg_1007.read()[0].is_01())? sc_lv<1>(): ((exitcond_reg_1007.read()[0].to_bool())? rev2_fu_567_p2.read(): rev1_reg_992.read());
}

void conv_3x3_strm::thread_tmp_i_fu_369_p2() {
    tmp_i_fu_369_p2 = (!ap_phi_mux_y_assign_phi_fu_291_p4.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_y_assign_phi_fu_291_p4.read() != ap_const_lv9_0);
}

void conv_3x3_strm::thread_tmp_i_mid1_fu_441_p2() {
    tmp_i_mid1_fu_441_p2 = (!i_fu_375_p2.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): sc_lv<1>(i_fu_375_p2.read() != ap_const_lv9_0);
}

void conv_3x3_strm::thread_tmp_i_mid2_fu_447_p3() {
    tmp_i_mid2_fu_447_p3 = (!exitcond_fu_427_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_fu_427_p2.read()[0].to_bool())? tmp_i_mid1_fu_441_p2.read(): tmp_i_fu_369_p2.read());
}

void conv_3x3_strm::thread_tmp_s_fu_527_p1() {
    tmp_s_fu_527_p1 = esl_zext<64,9>(x_assign_mid2_fu_433_p3.read());
}

void conv_3x3_strm::thread_x_1_fu_316_p2() {
    x_1_fu_316_p2 = (!ap_phi_mux_x_phi_fu_256_p4.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(ap_phi_mux_x_phi_fu_256_p4.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void conv_3x3_strm::thread_x_2_fu_333_p2() {
    x_2_fu_333_p2 = (!ap_phi_mux_x1_phi_fu_268_p4.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(ap_phi_mux_x1_phi_fu_268_p4.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void conv_3x3_strm::thread_x_assign_2_fu_501_p2() {
    x_assign_2_fu_501_p2 = (!x_assign_mid2_fu_433_p3.read().is_01() || !ap_const_lv9_2.is_01())? sc_lv<9>(): (sc_biguint<9>(x_assign_mid2_fu_433_p3.read()) + sc_biguint<9>(ap_const_lv9_2));
}

void conv_3x3_strm::thread_x_assign_mid2_fu_433_p3() {
    x_assign_mid2_fu_433_p3 = (!exitcond_fu_427_p2.read()[0].is_01())? sc_lv<9>(): ((exitcond_fu_427_p2.read()[0].to_bool())? ap_const_lv9_0: ap_phi_mux_x_assign_phi_fu_303_p4.read());
}

void conv_3x3_strm::thread_y_assign_2_fu_395_p2() {
    y_assign_2_fu_395_p2 = (!ap_phi_mux_y_assign_phi_fu_291_p4.read().is_01() || !ap_const_lv9_2.is_01())? sc_lv<9>(): (sc_biguint<9>(ap_phi_mux_y_assign_phi_fu_291_p4.read()) + sc_biguint<9>(ap_const_lv9_2));
}

void conv_3x3_strm::thread_y_assign_2_mid1_fu_553_p2() {
    y_assign_2_mid1_fu_553_p2 = (!y_assign_reg_287.read().is_01() || !ap_const_lv9_3.is_01())? sc_lv<9>(): (sc_biguint<9>(y_assign_reg_287.read()) + sc_biguint<9>(ap_const_lv9_3));
}

void conv_3x3_strm::thread_y_assign_mid2_fu_455_p3() {
    y_assign_mid2_fu_455_p3 = (!exitcond_fu_427_p2.read()[0].is_01())? sc_lv<9>(): ((exitcond_fu_427_p2.read()[0].to_bool())? i_fu_375_p2.read(): ap_phi_mux_y_assign_phi_fu_291_p4.read());
}

void conv_3x3_strm::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_310_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond1_fu_310_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            break;
        case 8 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_327_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond2_fu_327_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            break;
        case 64 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp2_iter3.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten_fu_415_p2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp2_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter4.read()) && 
  esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp2_iter3.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp2_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp2_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, exitcond_flatten_fu_415_p2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp2_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

void conv_3x3_strm::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_stream_V_din\" :  \"" << out_stream_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"out_stream_V_full_n\" :  \"" << out_stream_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_stream_V_write\" :  \"" << out_stream_V_write.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_stream_V_dout\" :  \"" << in_stream_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_stream_V_empty_n\" :  \"" << in_stream_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_stream_V_read\" :  \"" << in_stream_V_read.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

